server:
  port: 8081
dubbo:
  scan:
    base-packages: com.hujian.basic.service
  application:
    name: jjmm
  protocols:
    p1:
      id: dubbo1
      name: dubbo
      port: 20881
      host: 0.0.0.0
  registry:
    address: zookeeper://127.0.0.1:2181
    #timeout: 6000